#pragma once

#define YUNIK_GTC_OPENGL_VERSION_MAJOR 4
#define YUNIK_GTC_OPENGL_VERSION_MINOR 4

#define YUNIK_GTC_DEFAULT_WINDOW_NAME "Yunik-GTC"
#define YUNIK_GTC_DEFAULT_WINDOW_WIDTH 960
#define YUNIK_GTC_DEFAULT_WINDOW_HEIGHT 540
